### ISSUE TITLE
Map tailwind css to antd design system 

### ISSUE THREAD

**Issue by sanathkr** [RareCamp/RareCamp#14]
We are using Tailwind CSS for implementation but Ant design system for the UI mocks. The design system provides consistency, professionalism, and brand. These are unconscious elements that all users will notice and associate with the product. So we can't really forgo them. We need to map Tailwind classes, or create new ones, to match with Ant design system. A few things to look for: color, padding, margin, typography, tables, background, border, fonts, grid layout.

Don't hesitate to create our own set of classes because it might help other developers in the future to easily follow our design pattern.

**Comment by sanathkr** [comment]
@pipesorter is this done?

**Comment by pipesorter** [comment]
@sanathkr We have created components like Button, Dropdown, Icon so far for the pages that we designed, I think as we go on to make other pages, we can add other reusable UI components. Probably we should include https://storybook.js.org/ stories for these design UI components at least.

**Comment by sanathkr** [comment]
Got it. As discussed in Slack, let Storybook be lower priority. Can you create a list of other components we have to create to close this issue?
