### ISSUE TITLE
Feasibility questionnaire

### ISSUE THREAD

**Issue by brettstack** [RareCamp/RareCamp#30]
Feasibility questionnaire logic defined in #17 

- [x] On login, fetch all Programs for that user. If the user has no programs, route them to the feasibility questionnaire
- [x] Answers are persisted to DynamoDB when Back or Next is clicked
- [x] On feasibility questionnaire page load, answers are retrieved from DynamoDB (questionnaire values are set)
- [x] Leaving and returning to the page should drop the user on the screen after the screen that has **all** of its answers stored in DynamoDB. If a screen has partial answers (e.g. they started filling out the screen and clicked Back), they should be dropped on the screen with partial answers.
- [x] On final screen, feasibility is determined based on #17. If the user has no Programs **and** has completed all screens/answers on the questionnaire, they should be shown this screen.
- [x] Clicking **Create Program** creates a new Program with the name **<< Disease Name entered by user >> Gene Therapy** and the default Projects and Tasks. Note that Projects and Tasks are always the same, regardless of answers.
- [ ] Tests

**Comment by sanathkr** [comment]
Default Program name  = "<< Disease Name entered by user >> Gene Therapy"

Ex: If user entered "SSMD" as disease name then the program name is "SSMD Gene Therapy"

**Comment by brettstack** [comment]
Makes sense. Updated issue.

**Comment by sanathkr** [comment]
Logic for feasibility:

If user enters "Don't Know" for any question => Feasible
If user enters "Mutation leads to a LOSS of function" **and** "< 1100 amino acids" => Feasible
Everything else is NOT Feasible
