### ISSUE TITLE
Connect UI with AppSync/GraphQL backend endpoint

### ISSUE THREAD

**Issue by sanathkr** [RareCamp/RareCamp#5]
@bboure created a sample AppSync integration for us. We need to add Cogntio auth to prevent public access and connect the UI with it as a next step.

- [x] Add Cognito auth to AppSync
- [x] Connect UI to AppSync
- [ ] Tests

### Acceptance Criteria

- [ ] Unauthenticated requests are rejected by AppSync
- [ ] On login, a getDisease request is made (it's okay if it returns 404; so long as it makes it through to the resolver/data source)

**Comment by bboure** [comment]
@sanathkr Cognito is already set as the default Auth for AppSync. See [here](https://github.com/RareCamp/RareCamp/blob/master/templates/graphql.yml#L11-L14)
