### ISSUE TITLE
Backend of Login/Signup workflow using Cognito

### ISSUE THREAD

**Issue by sanathkr** [RareCamp/RareCamp#7]
Build the backend of Login/Signup workflow using Cognito to include Google authentication.

- [x] Create Cogntio Resources in Serverless Framework
- [x] Hook up UI
- [ ] Tests

### Acceptance Criteria

- [x] User can register with email + password (auto-verified in cognito; immediately logged in)
- [ ] User receives welcome email
- [x] User can login with email+password
- [x] User can reset password

**Comment by brettstack** [comment]
The current state is that we accept email signup and a DynamoDB entry for the user is inserted on login (if it doesn't exist). We need to update this to allow for social signins as well as custom emails.

**Comment by mitshubh** [comment]
Do we want to allow logins via social signins? A social account hack may result in an exposure of PHI/PII though this portal

**Comment by brettstack** [comment]
I think that's fine since it's the user's choice.

**Comment by mitshubh** [comment]
To me this the purpose of this portal seems very different from the other social applications. Is there a demand from the potential customers to have this feature?

**Comment by sanathkr** [comment]
Yeah, social logins are actually more secure than maintaining our own logins IMO because we are relying on 3p to maintain security than doing it ourselves.

**Comment by sanathkr** [comment]
@brettstack what is the "Google App" here mean? Can you elaborate?

**Comment by brettstack** [comment]
For social login, you need to create an integration in your Google Account, I believe Google calls these "Apps"?

**Comment by sanathkr** [comment]
Got it. Social login is not for MVP, so let's skip creating the app for now

**Comment by Dinesh5799** [comment]
@sanathkr I think I have fair understanding of AWS Congito & various other components. I've been working on AWS for almost 2 years. I am interested in contributing to RareCamp. Can you please let me know where can I start from ?

**Comment by sanathkr** [comment]
@Dinesh5799 Thank you so much for your interest in contributing! I just sent you a Slack invite to your LinkedIn DM. Let's connect on Slack to discuss next steps. 

#36 contains the latest UX designs if you want to take a peek before our convo. Checkout the walkthrough video hhere - https://www.youtube.com/watch?v=wAPUb0P5quY
